//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int Question_Id { get; set; }
        public string Question_Name { get; set; }
        public string Option_one { get; set; }
        public string Option_two { get; set; }
        public string Option_three { get; set; }
        public string Option_four { get; set; }
        public string Question_Answer { get; set; }
        public string Test_Name { get; set; }
    }
}
